---
# 需要加载的模型所在路径
model_path: ''
# 类别文件路径
classes_path: model_data/voc_classes.txt
#先验框对应的txt文件
anchors_path: model_data/yolo_anchors.txt
#先验框索引
anchors_mask:
  - - 6
    - 7
    - 8
  - - 3
    - 4
    - 5
  - - 0
    - 1
    - 2
#用于预测的图像高宽，需要与模型训练时一致
input_shape:
    - 416
    - 416
# 只有得分大于阈值的预测框才会被保留下来
confidence: 0.5
# 非极大抑制所用到的nms_iou大小
nms_iou: 0.3
# 一张图最多有多少个检测框
max_boxes: 100
# 控制是否使用letterbox_image对图像进行不失真的resize
letterbox_img: False
...